### PR TITLE
Fix LFNSiteByLastUpdate for /store/group. Fix #4429

### LINKED ISSUE #4429: if source&dest site is the same it deletes files from /store/group
Please see corresponding issue:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/879.html
and here is the problem: https://github.com/dmwm/AsyncStageout/blob/master/src/couchapp/AsyncTransfer/views/LFNSiteByLastUpdate/map.js

Currently ASO is patched on production not to delete anything from store/group.

@HassenRiahi can you set highest prio and would be good to have it in this release.

### PR DESCRIPTION
**Pull request by HassenRiahi**

### CODE REVIEW

**Comment by HassenRiahi** [comment]
pls review

**Comment by AndresTanasijczuk** [comment]
@HassenRiahi Why not start using doc.source_lfn directly?

**Comment by belforte** [comment]
was this happening because we are still using /store/temp/group ?
so we may need to revisit when fixing and make sure there is consistency
https://github.com/dmwm/CRABServer/issues/4907
(maybe all is OK, I add this comment only as a reminder to verify)

**Comment by HassenRiahi** [comment]
> Why not start using doc.source_lfn directly?

@AndresTanasijczuk you are right

**Comment by HassenRiahi** [comment]
Patch updated. Pls review.

File: src/couchapp/AsyncTransfer/views/LFNSiteByLastUpdate/map.js [hunk 1]
```diff
@@ -7,13 +7,6 @@ function complete_job(doc, req) {
 
 function(doc) {
 	if(doc.lfn && complete_job(doc)){
```
Comment (AndresTanasijczuk) [inline src/couchapp/AsyncTransfer/views/LFNSiteByLastUpdate/map.js]: if (doc.source_lfn && complete_job(doc)) {

Comment (juztas) [inline src/couchapp/AsyncTransfer/views/LFNSiteByLastUpdate/map.js]: also why need additional function `complete_job`, while it can be changed to doc['state']  == 'done'
